apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wms-route
  namespace: wms
spec:
  parentRefs:
    - name: wms-gateway
  hostnames:
    - app.datanetwork.online
  rules:
    # ðŸ”¹ API traffic â†’ Backend
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: backend
          port: 80

    # ðŸ”¹ Everything else â†’ Frontend
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80
