apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-config
  namespace: wms
type: Opaque
stringData:
  config.yaml: |
    tunnel: k8s-envoy
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - hostname: app.datanetwork.online
        service: http://envoy-wms-wms-gateway-00260609.envoy-gateway-system.svc.cluster.local:80
      - hostname: api.datanetwork.online
        service: http://envoy-wms-wms-gateway-00260609.envoy-gateway-system.svc.cluster.local:80
      - service: http_status:404
