apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: wms
type: Opaque
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiY2ZkOGRlNjU0YmZhZWY0MGZkY2U4ZDZiNGQ2YmUxZTEiLCJUdW5uZWxTZWNyZXQiOiJjdmVZVVlVQ0UzeUN4WENocUl0YW0zRDM1M1hRQ084N1R3UlArR09ndjBNPSIsIlR1bm5lbElEIjoiNGIyMDBiZDAtZjc3ZC00Y2E1LTllNzUtY2I1NTVkODNkODFlIiwiRW5kcG9pbnQiOiIifQ==
